### ISSUE TITLE
Flash messages

### ISSUE THREAD

**Issue by ziguane** [gitblit/fathom#13]
Hello,

I'am using Controllers.
What should I do to set a flash message ( error or success ) in java and template sides ?

Thank in advance

**Comment by gitblit** [comment]
I subclass controller and wrote these methods which use localized flash messages.

```java
protected void setSuccess(String messageKey, Object... args) {
    getContext().getSession().getFlash().success(getContext().getApplication().getMessages().get(messageKey, getContext(), args));
}

protected void setError(String messageKey, Object... args) {
    getContext().getSession().getFlash().error(getContext().getApplication().getMessages().get(messageKey, getContext(), args));
}
```

Then in my Pebble templates I access the flash ...

```html
{% if flash.hasSuccess() %}
    <p>{{ flash.getSuccess() | raw }}</p>
{% elseif flash.hasError() %}
    <p>{{ flash.getError() | raw }}</p>
{% endif %}
```

**Comment by ziguane** [comment]
It seems simple.

....
@Path
public class PublicController extends Controller {
	@GET("/")
	public void index() {
getContext().getSession().getFlash().success(getContext().getApplication().getMessages().get("msgtest", getContext()));

		getResponse().render("index");
}


in **all** messages properties files

msgtest=Hello world !

....
index.peb

FOR DEBUG {{flash}}

{% if flash.hasSuccess() %}
    <p>{{ flash.getSuccess() | raw }}</p>
{% elseif flash.hasError() %}
    <p>{{ flash.getError() | raw }}</p>
{% endif %}


....
 the index.peb generate only " FOR DEBUG FlashMessages{messages=[]} "




I'am using Fathom 0.9.2
What is missing ?

**Comment by gitblit** [comment]
Confirm....

1. `conf/messages.properties` is on the classpath
2. `conf/messages.properties` has your expected content
3. Put a breakpoint on the line `getResponse().render("index")` and confirm that the flash container in the session has the content you expect.
4. Consider using Flash for inter-request messages, not intra-request messages (i.e. you can just bind a message to the local context and directly use it in the template rather than using session flash).

**Comment by ziguane** [comment]
1. YES : conf/messages.properties is on the classpath
2. YES : conf/messages.properties has your expected content
3. NO : Put a breakpoint on the line getResponse().render("index") and confirm that the flash container in the session has the content you expect.
     context / response / locals
     {appVersion=1.0.0-SNAPSHOT, bootDate=Tue Dec 06 15:24:09 AST 2016, appName=CR2017, flash=FlashMessages{messages=[]}}
4. So, Flash messages are availables for the next request ?

Missing some docs about it :-)

**Comment by ziguane** [comment]
I was checking this [docs](http://fathom.gitblit.com/)
I'll try with a redirect
Thanks

**Comment by ziguane** [comment]
Checked ! You were right !!
Flash messages are availables for the next request !

**Comment by gitblit** [comment]
Great.  That is the intended use of Pippo's Flash.
