### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by abdelgadir** [gitblit/fathom#8]
Hi,
Great project - thank you very much for the time and effort.
Any chance for merging the Pippo controller improvements (declarative stuff and other improvements) back into Pippo.
thanks

**Comment by gitblit** [comment]
Parts of it are possible - that will depend on approval by @decebals. One issue was Pippo was holding back on adopting J8.  That's no longer the case.  Worst-case we could upstream a new controllers module that contains Fathom's declarative controller improvements.

**Comment by abdelgadir** [comment]
Fantastic - thanks James.
I noticed fathom depends on Pippo 0.6 whereas Pippo is now on version 0.7.  My concern was that if fathom adds more and more improvements which are not merged upstream it could mean fathom will have to depend on an increasingly older version of Pippo as the upstream Pippo project moves on and therefore it becomes more difficult to merge due to version gaps. I did notice you are also a Pippo contributor so I am sure this won't be a major concern :)

thanks again for your quick reply.

**Comment by gitblit** [comment]
Fathom 0.7 depends on Pippo 0.7 - docs are out-of-date.
Fathom 0.8-SNAPSHOT depends on Pippo 0.8-SNAPSHOT.

This is not a coincidence  :)

**Comment by abdelgadir** [comment]
great!

**Comment by decebals** [comment]
I appreciate the work of @gitblit to Pippo and Fathom (I enumerated only two projects). The fathom-rest module improves considerable the `Controller` concept from Pippo and add declarative support for REST.
It's super declarative (maybe a little too declarative for my taste :smile: ) and productive. I am OK to upstream these improvements to Pippo. I don't know how much work is to extract and adapt the fathom-rest module for Pippo (to remove Guice dependency for example).
My wish is to use a single `Controller` concept.
I am open to discussions about this subject.

**Comment by abdelgadir** [comment]
Thank you Decebals - I too appreciate all these projects :) 
I understand the need to remove some of these dependencies. For example, since Pippo can be used with CDI/Spring etc, it shouldn't have a dependency on Guice so yes some effort may be needed.

I see your point with respect to declarative style. IMHO the declarative style is often very convenient  -  I am used to JAX-RS and fathom is close in this regard. Particularly, the extractor concept is great and very useful. Also, I think fathom declarative style overcomes Pippo hard coded action method names when routing e.g., "pippo.getApplication().GET("/contact/{id}", ContactsController.class, "getContact");" will break if I rename the getContact action method. Although I am not sure how java 8 method references i.e., the '::' notation might help here.

some of fathom declarative improvements may not be a good idea to merge upstream, for example, I didn't quite understand the need for  '@Return' annotation and its use case and its seems somewhat redundant - why not just rely on the method signature's return type/throws clause? if it is for translated error messages, I could simply return an error code which can then be translated by another interceptor or something.

so I think the vast majority of the fathom controller improvements are great to merge upstream with Pippo but probably not all of them.

thanks

**Comment by decebals** [comment]
> so I think the vast majority of the fathom controller improvements are great to merge upstream with Pippo 

Definitely. The start it's always hard. Maybe when we have a little time we do the move.

**Comment by gitblit** [comment]
Discussion moved to decebals/pippo#237
